#!/bin/bash

source=$1
target=$2

if [ -z "$source" ]; then
  echo "Give source pls."
  exit 1
fi

if [ -z "$target" ]; then
  echo "Give target pls."
  exit 1
fi


read -p "Are you sure you want to dd $source to $target [y/n] " yn

case $yn in
  [Yy]*)
    sudo dd if=$source of=$target bs=8M status=progress;
    ;;
  [Nn]*)
    exit;
    ;;
esac

echo "Syncing!"
sync
