#!/bin/bash
#
case $BLOCK_BUTTON in
  3)
    xbacklight -set 5
  ;;
  4)
    xbacklight -inc 10
  ;;
  5)
    xbacklight -dec 10
  ;;
esac
val=$(printf "%.0f" $(xbacklight -get))
pkill -RTMIN+3 i3blocks

echo "$val%"
echo "$val%"

normal="#F2EB85"
echo $normal
