#!/usr/bin/python3.5
import psutil

def format(rawdata, end):
    if end in "":
        print("in")

color_danger = "#FF0000"
color_normal = "#F2EB85"

mem = psutil.virtual_memory()
print(mem)

print(mem.available)

print((mem.available / (1024*1024)))
print((mem.used / (1024*1024)))
